### ISSUE TITLE
Only the standardized name spelling is internationally recognized 

### ISSUE THREAD

**Issue by icanzilb** [philipptrenz/covidpass#14]
Bulgarian and Greek certificates contain the name spelled in cyrillic and greek respectively as shown below:

![690A88D1-2C3D-439F-8D09-51A6111F0EBB](https://user-images.githubusercontent.com/633862/124736338-30267280-df17-11eb-90f7-4a43bb2ec69f.jpeg)

It might be really useful if besides the main spelling the pass also contains the standardized spelling (described in the OpenAPI spec) so it matches the way it's written in a passport or an id card to aid folks who are traveling internationally

**Comment by icanzilb** [comment]
For completeness here's the fields I'm mentioning in the issue's description:

https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/main/DCC.combined-schema.json#L115-L123

https://github.com/ehn-dcc-development/ehn-dcc-schema/blob/main/DCC.combined-schema.json#L134-L142

**Comment by philipptrenz** [comment]
Thanks for this clear elaboration. Again, you're absolutely right!

**Comment by philipptrenz** [comment]
Hint to myself: Just saw, that `fnt` is the only required property within `nam`. this must be taken into account

**Comment by philipptrenz** [comment]
`fnt` and `gnt` are formatted after ICAO 9303 (uppercase letters, `>` instead of spaces or hyphens), so that the displayed text on the pass would be for example:  

```
DCERVENKOVA<PANKLOVA, JIRINA<MARIA<ALENA
```

instead of (currently)

```
d'Červenková Panklová, Jiřina-Maria Alena
```

I think that negatively affects the appearance and readability of the pass. And, as machine readability after ICAO 9303 is not needed here, I would suggest some kind of compromise.

**Idea 1**: Keep the current data (where available) on the front side of the pass and add the ICAO 9303 variant to the backside of the pass.

**Idea 2**: Use the ICAO 9303 variant, replace `>` with spaces and capitalize the words afterwards. Hyphenated double names could be recovered with some similarity algorithm comparing to `fn` and `gn`, if available.

@donatuswolf What is your opinion from a user experience and design perspective?

**Comment by philipptrenz** [comment]
Closed due to inactivity
