### ISSUE TITLE
Showing Greenpass on Apple Watch

### ISSUE THREAD

**Issue by ghost** [philipptrenz/covidpass#64]
While the Greenpass does appear on the Apple Watch, it is not possible to scan it, since the corners are cut off. It would be nice if it was zoomed out a little bit, so that every part of the code is visible on the watch face. As of now, I have to save a copy in my Gallery since I can zoom out of pictures there.
Thank you for keeping it simple and useful.

**Comment by donatuswolf** [comment]
Hi, we also ran into this problem, but really can't do anything about it. the problem only appears on the latest Apple Watch and somehow apple didn't check the screen size. Since iOS 15.4 apple has it's own way to add the certificate (at least the vaccination one) to the Apple wallet and there they fixed it.
